### ISSUE TITLE
How does this work in the new release?

### ISSUE THREAD

**Issue by kolbdog3333** [theMK2k/Media-Hoarder#46]
You put in the new relase this make series clickable and expand to episodes listing for the selected series, show affected number of episodes vs. total number of episodes?

How does that new feature work?

**Comment by kolbdog3333** [comment]
Same with this one: 
 remove the episodes section (in favor of episodes sections for all listed series)

**Comment by theMK2k** [comment]
Sorry, but I think I can't make sense of your question. Could you please provide some screenshots if you refer to something that is already there?

**Comment by kolbdog3333** [comment]
Look in the Readme its the first two items in the Done list for tv series:
Series: Media Property Dialog

    make series clickable and expand to episodes listing for the selected series, show affected number of episodes vs. total number of episodes
    remove the episodes section (in favor of episodes sections for all listed series)

**Comment by theMK2k** [comment]
Oh yes, the Media Property Dialog is the dialog that pops up when you click a property, e.g.:

- video resolution ("HD", "4k")
- age rating ("6+", "18+", ...)
- genre ("Action", "Animation", ...)
- cast
- company

etc.

That dialog provided sections "x movies", "y series" and (if you opened the dialog up in the context of a series) "z episodes".

That was suboptimal because the user might be interested - right within that dialog - to which episodes of any series listed in the dialog, that property applies to.

Sorry, lots of text. Here are some screenshots how it's implemented in the latest version:

1. I clicked the "Animation" genre (red arrow) and the dialog opens up (center of the screen)

![image](https://github.com/theMK2k/Media-Hoarder/assets/16878526/505f2f72-f42a-4608-bd70-89e1bbda3dea)

Now the dialog presents number of movies and number of series.

2. When clicking "movies" in the dialog, I get the list of movies that have the "Animation" property:

![image](https://github.com/theMK2k/Media-Hoarder/assets/16878526/0012faad-83a4-4938-aaed-77befa97d19d)

3. When clicking "series" in the dialog, I get the list of series that have the "Animation" property:

![image](https://github.com/theMK2k/Media-Hoarder/assets/16878526/f88c9ee4-a5cd-4ff7-a3b5-aa7108be47df)

---

Anything up to this point wasn't new, but this:

4. With the list of series expanded, I can click on a series and it will further expand to it's episodes.

Of course this doesn't make much sense with the "Animation" genre as the episodes are most likely all "Animation" if the series is "Animation", but for the sake of the current example:

![image](https://github.com/theMK2k/Media-Hoarder/assets/16878526/fb3dca05-d82a-47f0-8e0a-b0b9e61088f8)

**Comment by theMK2k** [comment]
A better example would be with cast. Here I opened up the dialog for "Troy Baker" to check in how many and which episodes of "Fullmetal Alchemist: Brotherhood" he is involved:

![image](https://github.com/theMK2k/Media-Hoarder/assets/16878526/e71154e0-0c0e-4179-bc9d-a93e348e61da)
