### ISSUE TITLE
While scanning: if episode poster not found, use series' poster

### ISSUE THREAD

**Issue by theMK2k** [theMK2k/Media-Hoarder#59]
Maybe for the missing episode poster picture if one cant be found it will use the series poster instead.

_Originally posted by @kolbdog3333 in https://github.com/theMK2k/Media-Hoarder/issues/37#issuecomment-1951434025_

**Comment by kolbdog323** [comment]
Hi this is still the same beta tester i just crated a new account.
I was just thinking if there is no image available for an episdoe it can use one of images found in the "photos" on the episode page since sometimes there are 1-3 or more pictures. And if you don't like the picture you can rescan the episode and it iwll choose another one of those images for the episode.
It might help with finding missing pictures for episodes since sometimes they have photos on the episode page.

**Comment by kolbdog323** [comment]
But it wont always work since not every epeisode has photos added on imdb but it would be a slight work around for it

**Comment by theMK2k** [comment]
In the next beta, Media Hoarder will show the series' poster if one for an episode wasn't found during scanning.

The feature work "out of the box", i.e. you will not have to rescan your collection for this.

**Comment by theMK2k** [comment]
> Hi this is still the same beta tester i just crated a new account. I was just thinking if there is no image available for an episdoe it can use one of images found in the "photos" on the episode page since sometimes there are 1-3 or more pictures. And if you don't like the picture you can rescan the episode and it iwll choose another one of those images for the episode. It might help with finding missing pictures for episodes since sometimes they have photos on the episode page.

thanks for bringing up other solutions for this, I have something in mind for the "provide own image for movies/series/episodes", stay tuned.

**Comment by theMK2k** [comment]
@kolbdog323 now that you have a new login, please visit all tickets and subscribe to those that you created with the old login, else you wouldn't know if something updated there.

**Comment by theMK2k** [comment]
Media Hoarder v1.4.0-b2 is uploaded, see https://github.com/theMK2k/Media-Hoarder/releases
