### ISSUE TITLE
Identifies movies as series

### ISSUE THREAD

**Issue by kolbdog323** [theMK2k/Media-Hoarder#61]
Just letting you kow there is an issue with media hoarder indetifing certain movies as series. FOr example i just tried adding the addams family series from 1964 without the year and it identified it as a movie same with the Pippi longstocking 1997 tv series it identified that as the Pippi Longstocking movie from 1997. I think you need to fix it so it only identifies series not movies with same name.

**Comment by theMK2k** [comment]
Hi @kolbdog323,

thanks for your feedback. Yes, the IMDB detection needs optimization here. I will let you know as soon as an updated version is available.

**Comment by kolbdog323** [comment]
Just suggestion maybe it will look for a page that has the words tv series in the actual page because all the tv series say tv series on the main sereis page maybe that might help for the issue of it accidentally identifying a movie as a series if you dont put the (start year to end year) in file name? Since if you go onto a tv series page it says TV Series then it shows the start year - end year after that?

**Comment by theMK2k** [comment]
Yes, IMDB provides certain types, like 'tv-series', 'tv-episode' or 'feature' in their data. We will leverage that.

**Comment by theMK2k** [comment]
In the upcoming v1.4.0-b6 we'll have an optimized IMDB entry detection where as soon as a Series source path is scanned, the IMDB search results are re-ranked by the media type ("TV Series" before "Movie").

I tested the optimized IMDB detection with both of your examples, here is the directory/file structure:

```
Series\The Addams Family
    Season01
        The Addams Family S01E01.mkv
        The Addams Family S01E02.mkv

Series\Pippi Longstocking (1997-1998)
    Season01
        Pippi Longstocking S01E01.mkv
        Pippi Longstocking S01E02.mkv

```

The results after scanning are as expected now:

![image](https://github.com/theMK2k/Media-Hoarder/assets/16878526/d4ef9fa6-2c37-45f8-95d8-6cde30c96706)

**Comment by theMK2k** [comment]
**v1.4.0-b6** is released. If you run v1.4.0-b5 it should also tell you about the update - please let me know if that worked for you also ;)

**Comment by theMK2k** [comment]
During the scan, Media Hoarder "sees" the new series and its directory is "Pippi Longstocking (1997-1998)".

As the directory does not contain the tt*, Media Hoarder performs a search on IMDB (like you would do by using the imdb.com site's search).

With the search, Media Hoarder gets a result (44 results for the search term "Pippi Longstocking".

Amongst the 44 results, we get the year (e.g. 1997 for both the movie and the series) as well as the information if it's a TV Series.

Now, with the optimization, the results get re-ranked by putting all TV Series entries to the top.

With the re-ranked results, Media Hoader now takes the first element in the list that additionally matches the year (1997). And this is now the Pippi Longstocking tv series instead of the movie.

**Comment by theMK2k** [comment]
The gist is: the search result on IMDB for "Pippi Longstocking" brings up the movie before the tv series. With the re-ranking we move the tv series entry up so that it will be chosen by Media Hoarder.

**Comment by kolbdog323** [comment]
Will that work for movies that have same name and release year as a tv show since some movies have same name and release year as a show but not always .

**Comment by theMK2k** [comment]
I would need to test that, too

**Comment by theMK2k** [comment]
that would then be a good candidate to test

**Comment by theMK2k** [comment]
No need to wonder anymore, I just enhanced the logging a bit and it works like this for **Movies** source path:

The search results will be completely stripped off TV Series and TV Episodes when the scanning is done on a Movies source path.
